## Let's Create Tensors

In [1]:
import tensorflow as tf


In [3]:
#zero dimensional tensor
zero_d = tf.constant(4)
zero_d
#notice the shape and data type of the tensor in the output

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [6]:
#one dimensional tensor
one_d = tf.constant([2,3,-5,0])
one_d
#modify an element by adding decimal point and observe the change! Uncomment the follwing lines of code:
# one_d = tf.constant([2,3.4,-5,0])
# one_d


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 2,  3, -5,  0], dtype=int32)>

In [9]:
#two dimensional tensor
two_d = tf.constant([[2,3,4],[4.5,-3,2]])
two_d

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2. ,  3. ,  4. ],
       [ 4.5, -3. ,  2. ]], dtype=float32)>

In [10]:
#three dimensional tensor
three_d = tf.constant([[[1,2,3],[-4,-5,6.7]],[[56,78,-23],[45,21,2]]])
three_d

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[  1. ,   2. ,   3. ],
        [ -4. ,  -5. ,   6.7]],

       [[ 56. ,  78. , -23. ],
        [ 45. ,  21. ,   2. ]]], dtype=float32)>

In [12]:
#Now you get it right? A higher dimensional tensor is just a combination of lower dimensional tensors!
#try to create a 4-D and 5-D tensor.

## Let's get additional information about these tensors using tensor attributes.

In [14]:
#check the dimension
three_d.ndim

3

In [15]:
#check the shape
three_d.shape

TensorShape([2, 2, 3])

In [16]:
#check the data type
three_d.dtype

tf.float32

In [20]:
#You can also change the data type of a tensor by using dtype parameter.
tf.constant([3,4,5],dtype = tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([3., 4., 5.], dtype=float32)>

In [25]:
#you can also type cast a tensor
threeD_casted = tf.cast(three_d, dtype = tf.int64)
threeD_casted

<tf.Tensor: shape=(2, 2, 3), dtype=int64, numpy=
array([[[  1,   2,   3],
        [ -4,  -5,   6]],

       [[ 56,  78, -23],
        [ 45,  21,   2]]])>

In [22]:
three_d.dtype

tf.float32

In [28]:
#tensors can also contain strings
string_tensor_1d  = tf.constant(['hello','there'])
string_tensor_1d

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'hello', b'there'], dtype=object)>

In [29]:
string_tensor_0d  = tf.constant("hello there!")
string_tensor_0d

<tf.Tensor: shape=(), dtype=string, numpy=b'hello there!'>

In [ ]:
#you must think that numpy arrays and tensors are kinda similar datastructures. However they are different from one another.

#### Same Same but different: Numpy arrays and Tensors





1. NumPy arrays: These are the n-dimensional structures you simply use for numerical computations in python.

*   They support simple operations like addition, multiplication, and indexing, and they are great for handling small to medium datasets.

* However, they don’t have built-in support for distributed computing (e.g., GPU acceleration) or automatic differentiation (useful for training machine learning models).

2. Tensor: While similar to NumPy arrays in shape and function, tensors are designed for high-performance tasks, especially in deep learning frameworks like TensorFlow or PyTorch. Tensors can:
* Be computed on devices like GPUs or TPUs.
* Support automatic differentiation, meaning they can track and compute gradients during backpropagation in neural networks.


So, while they look alike and can often be used interchangeably for basic tasks, tensors have extra capabilities built for deep learning and scalability.

In [32]:
# On this note, let's convert a numpy array into tensor.
import numpy as np
np_array = np.array([3,42,-4])
tensor_converted  = tf.convert_to_tensor(np_array)
tensor_converted

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 3, 42, -4])>

In [ ]:
#Visit this page to explore important methods, modules etc in tensorflow. You will come across some methos that are quite similar to the ones that numpy arrays have.
#https://www.tensorflow.org/api_docs/python/tf/all_symbols

### Indexing the Tensors

In [36]:
#let's use the tensors we created before. Recall how indexing works in numpy arrays. Start!
#Index the 2nd element in a 1-D array
one_d[1]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [41]:
#index the bottom last element from the 2-D array
two_d[-1,-1]   #Yes, you can use the negative index numbers as well

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [42]:
#DIY: index an element out of a 3-D tensor

In [46]:
#SLICE A TENSOR!
##use the syntax tensor_name[start_index:stop_index:step_value]

one_d[1:4]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 3, -5,  0], dtype=int32)>

## Mathematical Operations on Tensors:

tf.math is a module in TensorFlow that provides a collection of mathematical functions and operations for tensor computations. It includes various functions to perform mathematical operations on tensors, which are the primary data structures used in TensorFlow.

link: https://www.tensorflow.org/api_docs/python/tf/math

In [48]:
#get the absolute value of a tensor
tf.math.abs(tf.constant([-4,-5,2]))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 2], dtype=int32)>

In [50]:
#absolute value of a complex number(a+bj) is calculated as a^2 + b^2
tf.math.abs(tf.constant(4+6j))

<tf.Tensor: shape=(), dtype=float64, numpy=7.211102550927978>

In [55]:
#addition
print('tensor 1:' ,one_d)
tensor_2 = tf.constant([3,4,5,6])
print('tensor 2:',tensor_2)
print('addition:',one_d + tensor_2)

tensor 1: tf.Tensor([ 2  3 -5  0], shape=(4,), dtype=int32)
tensor 2: tf.Tensor([3 4 5 6], shape=(4,), dtype=int32)
addition: tf.Tensor([5 7 0 6], shape=(4,), dtype=int32)


In [56]:
#you can also write it as
print(tf.add(tensor_2,one_d))


tf.Tensor([5 7 0 6], shape=(4,), dtype=int32)


In [58]:
#use subtract method to get the difference between two tensors
print(tf.subtract(tensor_2,one_d))
#there are similar methods for divide, multiply etc.

tf.Tensor([ 1  1 10  6], shape=(4,), dtype=int32)


In [61]:
#adding a scalar to a tensor works as well. It results into a new tensor that contains the number added to each element of the tensor.
one_d  + 2

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 4,  5, -3,  2], dtype=int32)>

In [61]:
#DIY: create tensors of various dimensionalities and perform computations betweem them.
#refer to the official documentation  https://www.tensorflow.org/api_docs/python/tf/math
#to explore more methods

### Ragged Tensors

Ragged tensors are a special type of tensor in TensorFlow designed to handle data with varying shapes in one or more dimensions. Unlike regular tensors, which require each dimension to have a consistent size, ragged tensors can accommodate sequences of varying lengths, making them useful for tasks where the input data isn't uniform.

In [68]:
#create a new tensor with distorted shape
tf.constant([[[3,4,5],
              [5,7]],
             [[4,3,3,3],
              [4,5,]]])

ValueError: Can't convert non-rectangular Python sequence to Tensor.

In [70]:
#to get rid of this error you need to create a ragged tensor
ragged_tensor = tf.ragged.constant([[[3,4,5],
              [5,7]],
             [[4,3,3,3],
              [4,5,]]])

In [71]:
ragged_tensor.shape

TensorShape([2, None, None])

### Sparse Tensors

Sparse tensors are a way to efficiently store and manipulate tensors (multi-dimensional arrays) that **contain a lot of zero values**. Instead of storing every element of the tensor, including zeros, sparse tensors only store the non-zero values along with their indices. This can save a significant amount of memory and computational resources.

In [77]:
#to create a sparse tensor you use tf.sparse.SparseTensor()
#Provide the "indices" where you want to store the non-zero values.
#Provide the non-zero values as "values" in form of a list.
#decide the shape of your sparse tensor and pass it to "dense_shape" parameter
sparse_tensor = tf.sparse.SparseTensor(indices = [[0,0],[1,2]],values = [1,2],dense_shape = [10,10])

In [76]:
#convert the sparse tensor to dense
tf.sparse.to_dense(sparse_tensor)

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

### Tensors vs Variables


* We have been using tf.constant() to create a tensor as all the tensors that have been created so far in this notebook are constants.**Constants** are the tensors whose value cannot be changed once it is created. When you want to keep the value fixed throughout the execution of the model, use constants.

* On the other hand, Variables in TensorFlow is a tensor whose value can be changed during execution. Variables are used to hold parameters of the model that are updated during training.



In [82]:
#creating a variable tensor
one_d_var = tf.Variable([2,3,4,5])
one_d_var

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

In [85]:
#modifying a variable tensor
one_d_var.assign([3,4,5,6])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([3, 4, 5, 6], dtype=int32)>

In [86]:
#let's try to modify a "constant" tensor we have created before
one_d.assign([42,4,5,5])
#got an error

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'